### PR TITLE
Optimize api stuff

### PR DESCRIPTION
**Pull request by BatedUrGonnaDie**
Authie will still trigger session stuff if you visit it logged in while in a browser, but this should fix it for all consumers of the api.

### CODE REVIEW

**Comment by BatedUrGonnaDie** [comment]
Blocked for now by weird behavior in authie.  Waiting to see if a total kill switch can be configured per controller.

**Comment by BatedUrGonnaDie** [comment]
Looks like as soon as you call `current_user` authie will run, so it will be disabled on all endpoints except the ones that need it still.

**Comment by BatedUrGonnaDie** [comment]
Did you want me to include the authie skip in health controller in this PR?

**Comment by glacials** [comment]
Sure, might as well.

**Comment by BatedUrGonnaDie** [comment]
Should be good to go with that now I believe.

**Pull request merged**
