### PR TITLE
Update migrations to remove depreciation warning

### PR DESCRIPTION
**Pull request by BatedUrGonnaDie**
Adds target rails version identifiers to migrations.

### CODE REVIEW

**Comment by glacials** [comment]
Interesting, never seen this syntax before. Can you point me to docs for this?

**Comment by BatedUrGonnaDie** [comment]
The best explanation I can find is this blog post on it: http://blog.bigbinary.com/2016/03/01/migrations-are-versioned-in-rails-5.html .  If you look into the past builds on travis though you can see the depreciation warnings for each migration that doesn't have the version identifier.

**Comment by BatedUrGonnaDie** [comment]
All new migrations generated will have a [5.0] added to the end.

**Comment by glacials** [comment]
Cool, that's good enough for me. Thanks for caring about all this stuff, it's super nice getting these deprecation warnings killed!

**Pull request merged**
