### PR TITLE
Update game page design

### PR DESCRIPTION
**Pull request by glacials**
Adds game box art, condenses export / race buttons, adds Twitch links, and adds some basic information about median run lengths to the game page.

beta splits io_games_zoe

### CODE REVIEW

**Comment by glacials** [comment]
🤔 this crashes on beta for really popular games like oot, sms, sm64, but I can't find an n+1 🤔

**Comment by BatedUrGonnaDie** [comment]
I'll review this tomorrow and see if I can find the root cause of the crash.

**Comment by glacials** [comment]
For some reason after rebasing on master and deploying to beta again, it works fine now and is even pretty fast??? Maybe something with the database upgrade, or one of the changes in master.

**Comment by glacials** [comment]
YOLO

**Pull request merged**
