### PR TITLE
Update to bootstrap 4

### PR DESCRIPTION
**Pull request by BatedUrGonnaDie**
Known issue is with the timeline background shows through for about 2 pixels, I was hoping you would be able to take a look and see if you could figure out why @glacials because I can't seem to figure it out.

Also some of the default styles have changed and I wasn't sure if you wanted to override those, like the font color.  I also applied a lot of margin classes to try and emulate the look of the live site the best that I could.

Some other key notes are that all col's have been upgraded one size to do bootstrap adding an XS size, which bumped everything up, all panels being converted to cards as best I could, and adding a few cards where it was appropriate.

### CODE REVIEW

**Comment by BatedUrGonnaDie** [comment]
Apparently bootstrap also now has tooltips in it (or it always did who knows), did you want to switch to those from tipsy?

**Comment by glacials** [comment]
Wow who knew. I don't have a strong preference without having seen how Bootstrap tooltips are to work with, so I'll let you decide which seems better.

**Comment by BatedUrGonnaDie** [comment]
[This page](https://getbootstrap.com/docs/4.1/components/tooltips/) shows everything related to tooltips and stuff.

**Comment by glacials** [comment]
I want to run this locally to visually inspect it but I'm getting this error after `docker-compose build && docker-compose up`:

```
File to import not found or unreadable: charts.
Load paths:
  /app/app/assets/config
  /app/app/assets/images
  /app/app/assets/javascripts
  /app/app/assets/stylesheets
  /app/lib/assets/bower_components
  /usr/local/bundle/bundler/gems/purecss-rails-a4c7a6c05bf4/app/assets/stylesheets
  /usr/local/bundle/gems/flat-ui-rails-0.0.2/vendor/assets/images
  /usr/local/bundle/gems/flat-ui-rails-0.0.2/vendor/assets/stylesheets
  /usr/local/bundle/bundler/gems/turbolinks-80216ce9d899/lib/assets/javascripts
  /usr/local/bundle/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /usr/local/bundle/gems/doorkeeper-4.3.1/app/assets/stylesheets
  /usr/local/bundle/gems/doorkeeper-4.3.1/vendor/assets/stylesheets
  /usr/local/bundle/gems/administrate-0.9.0/app/assets/javascripts
  /usr/local/bundle/gems/administrate-0.9.0/app/assets/stylesheets
  /usr/local/bundle/gems/selectize-rails-0.12.4.1/vendor/assets/javascripts
  /usr/local/bundle/gems/selectize-rails-0.12.4.1/vendor/assets/stylesheets
  /usr/local/bundle/gems/momentjs-rails-2.20.1/vendor/assets/javascripts
  /usr/local/bundle/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /usr/local/bundle/gems/datetime_picker_rails-0.0.7/app/assets/fonts
  /usr/local/bundle/gems/datetime_picker_rails-0.0.7/app/assets/javascripts
  /usr/local/bundle/gems/datetime_picker_rails-0.0.7/app/assets/stylesheets
  /usr/local/bundle/gems/actioncable-5.1.5/lib/assets/compiled
  /usr/local/bundle/gems/actionview-5.1.5/lib/assets/compiled
  /app/node_modules
  /usr/local/bundle/gems/popper_js-1.12.9/assets/javascripts
  /usr/local/bundle/gems/bootstrap-4.1.0/assets/stylesheets
  /usr/local/bundle/gems/bootstrap-4.1.0/assets/javascripts
  /usr/local/bundle/gems/bootswatch-4.1.0/assets/stylesheets
  /usr/local/bundle/gems/bootswatch-4.1.0/assets/javascripts
  /usr/local/bundle/gems/font-awesome-sass-5.0.9/assets/stylesheets
  /usr/local/bundle/gems/font-awesome-sass-5.0.9/assets/fonts
  /usr/local/bundle/gems/bootstrap-4.1.0/assets/stylesheets
  /usr/local/bundle/gems/bootswatch-4.1.0/assets/stylesheets
  /usr/local/bundle/gems/font-awesome-sass-5.0.9/assets/stylesheets
```

**Comment by BatedUrGonnaDie** [comment]
Should be fixed.

**Comment by BatedUrGonnaDie** [comment]
I'm not sure how much I'll be able to do for point 6 because bootstrap toggle isn't updated for bootstrap 4 and it seems to be abandoned.  I already did a janky hack to get the styling as close as I could.  Other than that one all the other should be do-able with ease.

**Pull request merged**
